### ISSUE TITLE
Show Views in the Class' Structure tool window

### ISSUE THREAD

**Issue by duemir** [jenkinsci/idea-stapler-plugin#102]
### What feature do you want to see added?

Lombok plugin somehow shows the generated items in the structured view. It'd be nice to show Stapler views in the structure as well. It will give more ways to discover and navigate to the class's views.

Here is a doodle that explains it hopefully:

![Screen Shot 2022-10-06 at 18 29 10](https://user-images.githubusercontent.com/348580/194263029-6347ecf8-003f-4724-9d74-ca508effc36a.png)

**Comment by duemir** [comment]
Lombok plugin details to use as reference:

* https://plugins.jetbrains.com/plugin/6317-lombok
* https://github.com/mplushnikov/lombok-intellij-plugin/blob/master/src/main/resources/META-INF/plugin.xml#L130
* https://github.com/mplushnikov/lombok-intellij-plugin/blob/master/src/main/java/de/plushnikov/intellij/plugin/extension/LombokStructureViewExtension.java

**Comment by jgreffe** [comment]
Hello @duemir,
could you detail "shows the generated items in the structured view". I'm not sure to understand how to access/enable this with lombok plugin? Do you mean file structure view?
