### ISSUE TITLE
Override organization issue templates for this repository

### ISSUE THREAD

**Issue by duemir** [jenkinsci/idea-stapler-plugin#110]
The https://github.com/jenkinsci/.github/tree/master/.github/ISSUE_TEMPLATE is very much Jenkins [plugin] oriented. It doesn't really apply here, especially Bug one. Override to be more JetBrains IntelliJ specific.

As the first step can just be disabled if possible.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by Jagrutiti** [comment]
Hey @duemir 

What are the steps for disabling it?

**Comment by duemir** [comment]
> Hey @duemir 
> 
> What are the steps for disabling it?

I don't know. I have not read the docs yet. I think I found and linked the right docs. 

I hoped maybe somebody with better knowledge of Github can contribute it quickly.
