### ISSUE TITLE
Move to jenkinsci and make more jenkins plugin development focused?

### ISSUE THREAD

**Issue by duemir** [jenkinsci/idea-stapler-plugin#43]
Stapler Framework is probably rarely used outside Jenkins development. A similar situation seems to be with Jelly and JEXL. Maybe this plugin should be renamed to "Jenkins Plugin Development Support" or something like that and moved to `jenkinsci` organization? 
Then it can contribute more different extensions which generally help with Jenkins [plugin] development.

**Comment by oleg-nenashev** [comment]
FTR https://groups.google.com/g/jenkinsci-dev/c/SZNh_cy3eu4 for the discussion on the Jenkins side.
https://plugins.jetbrains.com/organizations/jenkins/ for the newly created JetBrains marketplace org

**Comment by jglick** [comment]
> moved to `jenkinsci` organization

FYI https://issues.jenkins.io/browse/INFRA-2908

**Comment by jglick** [comment]
If we are moving out of @stapler, I might recommend the @jenkins-infra project under the principle that @jenkinsci should be used for software either packaged into Jenkins or used during a build of Jenkins, but I have no strong opinion.

**Comment by duemir** [comment]
The moving part is done. Should it be re-focused? What would it mean? Just a rename at first and then the addition of the features specific to Jenkins development?

**Comment by jglick** [comment]
> the addition of the features specific to Jenkins development

FYI the analogous NetBeans plugin is actually broken into two pieces for historical reasons, one limited to Stapler and one specific to Jenkins (https://github.com/stapler/netbeans-stapler-plugin/tree/714a93faf266fd2e3175f7344fec05316a0a2803/stapler-plugin/src/main/java/org/kohsuke/stapler/netbeans/plugin vs. https://github.com/stapler/netbeans-stapler-plugin/tree/714a93faf266fd2e3175f7344fec05316a0a2803/jenkins-plugin/src/main/java/org/kohsuke/stapler/netbeans/jenkinsdev). Given that Stapler is no longer even advertised for use outside Jenkins, this split does not make sense.

**Comment by duemir** [comment]
Trademark question was cleared in Google Groups discussion https://groups.google.com/g/jenkinsci-dev/c/B8Z23mKc7fo/m/LY9ehEjLAQAJ
