### ISSUE TITLE
Why not publish to Marketplace

### ISSUE THREAD

**Issue by UkonnRa** [jenkinsci/idea-stapler-plugin#44]
> This release is not yet published on Jetbrains Marketplace.

Just wondering why. Since lots of plugin developers may prefer using Intellij as their IDE so a Jelly highlighter/hinter may help a lot

**Comment by duemir** [comment]
I am afraid I do not have access to the current marketplace listing, so I simply couldn't do it when I marked that release.
If I understand correctly, at the moment, only @kohsuke can do it. 
I didn't want to bother KK since he is probably busy with his startup. Also, a pathway for handing the release process over to the community (like with Jenkins) is not established. On the other hand, releasing this project is not as frequent a process as Jenkins.

**Comment by kohsuke** [comment]
Happy to let somebody else take over the release process. How can I do that?

**Comment by duemir** [comment]
[JetBrains Marketplace now has Organizations](https://plugins.jetbrains.com/docs/marketplace/organizations.html). @oleg-nenashev can Jenkins project own such an organization so that IntelliJ Stapler Plugin can belong to the Org, not any individual maintainer?

**Comment by kohsuke** [comment]
Yes, this looks to be a perfect mechanism for that. I'll wait for somebody more responsive to create an org and add me to it, then I can transfer the plugin.

**Comment by oleg-nenashev** [comment]
Sorry for missing the ping. We have no org, but we can create one. Could you please start a thread in the Jenkins developer mailing list?

**Comment by duemir** [comment]
Hi @kohsuke 
I have prepared a release for publishing https://github.com/jenkinsci/idea-stapler-plugin/releases/tag/2.0.0 
After publishing, it should be possible to do a [Plugin transfer](https://plugins.jetbrains.com/docs/marketplace/organizations.html#plugin-transfer)

**Comment by duemir** [comment]
As far as I understand the new version would go through some kind of review. If it is blocked for any reason, let me know @kohsuke and I will try to fix.

**Comment by offa** [comment]
Are there any news?

**Comment by duemir** [comment]
> Are there any news?

I am guessing @kohsuke is a bit too busy at the moment to do the release.

So, no news. Releases are still only available for manual installation

**Comment by duemir** [comment]
I see the plugin is now under the Jenkins organization and the latest version is pending approval from JetBrains
Thank you @kohsuke!

**Comment by kohsuke** [comment]
@duemir it's published now and hopefully with this now you can post updates at your own pace. Thanks once again for your patience.

**Comment by duemir** [comment]
No worries @kohsuke 🙇 . You must be really busy with the startup. I do not have much time to work on this myself.
