### ISSUE TITLE
AST doesn't seem to be rebuilt, so we end up having stale references.

### ISSUE THREAD

**Issue by duemir** [jenkinsci/idea-stapler-plugin#5]
- AST doesn't seem to be rebuilt, so we end up having stale references.
   Who's supposed to trigger the AST reconstruction?
        -> Added ChangeVisitorImpl and that fixed it.

**Comment by duemir** [comment]
This is a task from Readme.txt. Might be already fixed need to double-check.

**Comment by timja** [comment]
I think we can leave this as its been 4 years without anyone reporting similar
