### ISSUE TITLE
Jelly file association disappeared

### ISSUE THREAD

**Issue by timja** [jenkinsci/idea-stapler-plugin#67]
### Version report

![image](https://user-images.githubusercontent.com/21194782/131995244-987653a7-9386-49fa-9812-bbe0607108fc.png)

- What Operating System are you using (both controller, and any agents involved in the problem)?

MacOS

### Reproduction steps

- Update to latest intellij from a previous version
- Update stapler plugin to latest version (2.0.2)
- Open a jelly file

### Results

Expected result:

Syntax highlighting

Actual result:

Rendered as a text file

### Work around

I was able to add an association myself via editor settings: 

`Editor => File types => Jelly`
Add *.jelly

cc @duemir

**Comment by duemir** [comment]
Same as #58. I thought I fixed it :( Some kind of edge case, probably. It still uses deprecated API after all.

**Comment by timja** [comment]
Will see what happens when I upgrade my other machine, been holding off though as I had a couple of other unrelated issues with the upgrade too

**Comment by duemir** [comment]
I got one more feedback about it. In their case filetype association with XML remained. A new Jelly file type was added without any associations. 😞

**Comment by duemir** [comment]
In #71 I have reverted the workaround that I did to "fix" #58. We should be back to old behaviour. 2021.2 no association between `*.jelly` and XML file type. 2021.1 and 2021.3 and newer should have it.
If you have manually added `*.jelly` to XML file type, it will override whatever plugin declares as far as I understand.
