### ISSUE TITLE
Auto-completion needs to work

### ISSUE THREAD

**Issue by duemir** [jenkinsci/idea-stapler-plugin#7]
- Auto-completion needs to work

**Comment by duemir** [comment]
This is a task from Readme.txt. Might be already fixed need to double-check.

**Comment by duemir** [comment]
Needs a better definition. Some autocompletion definitely work but IntelliJ definitely have no idea about HTML in between Jelly tags (#40)

**Comment by Zastai** [comment]
Aside from HTML there is also an issue completing namespaced tags.

Given a Jelly containing

```jelly
<?jelly escape-by-default='true'?>
<j:jelly xmlns:j="jelly:core" xmlns:f="/lib/form">

  <f:entry title="Foo" field="bar">
    <f:select/>
  </f:entry>

</j:jelly>
```

go to the `<f:select/>` and removed the `select` leaving just `<f:/>`. Now press `Ctrl-Space` with the caret after the `:`.
This will show a nice list of completions, including the `f:` prefix - but when selecting one, it will inset that whole entry at the caret, duplicating the `f:`.

If you start with `f:se` before pressing `Ctrl-Space`, then it replaces the `se`, still duplicating the `f:`. So there might be some "replace word around point" logic involved, with `:` not considered a word constituent.

**Comment by timja** [comment]
> Aside from HTML there is also an issue completing namespaced tags.
> 
> Given a Jelly containing
> 
> <?jelly escape-by-default='true'?>
> <j:jelly xmlns:j="jelly:core" xmlns:f="/lib/form">
> 
>   <f:entry title="Foo" field="bar">
>     <f:select/>
>   </f:entry>
> 
> </j:jelly>
> go to the `<f:select/>` and remove the `select` leaving just `<f:/>`. Now press `Ctrl-Space` with the caret after the `:`. This will show a nice list of completions, including the `f:` prefix - but when selecting one, it will insert that whole entry at the caret, duplicating the `f:`.
> 
> If you start with `f:se` before pressing `Ctrl-Space`, then it replaces the `se`, still duplicating the `f:`. So there might be some "replace word around point" logic involved, with `:` not considered a word constituent.

Created as https://github.com/jenkinsci/idea-stapler-plugin/issues/190 without seeing this comment

----

This task isn't clear and actionable so I don't think there's value in keeping it open
