### ISSUE TITLE
Is Stapler Facet even needed?

### ISSUE THREAD

**Issue by duemir** [jenkinsci/idea-stapler-plugin#87]
### What feature do you want to see added?

Stapler Facet is empty. It does not contain any framework-specific settings that need to be configured on the module.
It is essentially just a toggle for a few features. 
Is it even necessary?

**Comment by duemir** [comment]
https://plugins.jetbrains.com/docs/intellij/facet.html
https://plugins.jetbrains.com/docs/intellij/project-structure.html#facet

There are currently no facet-specific configs and no facet-based tool windows. As stated above, it is used as a flag in JEXL checker, but that is about it.

Not really needed a the moment, it seems, but can there be a reason to use it?

**Comment by jgreffe** [comment]
Currently Facet is used only here: https://github.com/jenkinsci/idea-stapler-plugin/blob/d8e237c865e88facd22eb79ba01933ee9f7d7441/src/main/java/org/kohsuke/stapler/idea/LocalXmlInspectionTool.java#L26
As a new jelly type file is introduced with #102, I think Facet is not useful anymore.
