### ISSUE TITLE
Jelly Core Schema is not complete

### ISSUE THREAD

**Issue by Zastai** [jenkinsci/idea-stapler-plugin#92]
### Jenkins and plugins versions report

Plugin base Jankins version is 2.289.1.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

Open any Jelly file that contains an `<f:entry>` element. Press `Ctrl-B` to go to its definition.

### Expected Results

`entry.jelly` validates fine

### Actual Results

An error is reported on `<j:out>` elements.
Using `Ctrl-B` on the `xmlns:j="jelly:core"` to navigate to the Jelly schema included in the plugin indeed does not include such an element.

### Anything else?

(Maybe this bug reporting form could/should be tailored; you don't need to have a Jenkins installation to edit code in an IDE, so asking about the Jenkins version seems a bit superfluous.)

**Comment by duemir** [comment]
> (Maybe this bug reporting form could/should be tailored; you don't need to have a Jenkins installation to edit code in an IDE, so asking about the Jenkins version seems a bit superfluous.)

Yes, agree. It is inherited from the @jenkinsci org. I haven't had much time to work on this to change it.

**Comment by duemir** [comment]
Noting that this annotation is most likely not from the standard XML schema validation code, but custom `org.kohsuke.stapler.idea.JellyAnnotator`. Starting from 2.0.5 it should report "Undefined jelly element" instead of generic "Undefined element" which can be confused with some out-of-box schema validation.

`out` element seems to be missing in the schema as well. I lack the knowledge of how those schemas were generated, though.

**Comment by jgreffe** [comment]
Hello @duemir,

I’ve seen your post on [google group](https://groups.google.com/g/jenkinsci-dev/c/yydy-vNDzuI).
It seems xsd are generated with this [script](https://github.com/jenkinsci/maven-jellydoc-plugin/blob/master/maven-jellydoc-plugin/schemagen-on-jelly.sh#L2-L7).
But it uses maven 1 with goal `tags:build` to create `target/taglib.xml` and `jelly-tags/*/target/taglib.xml`, and I can’t find any equivalent for maven 3 :confused:

More, I tried to `mvn clean install` this [repo](https://github.com/jenkinsci/jelly), but no `taglib.xml` related is generated :confused:
